/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface About {
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'summary' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Experience {
  'id' : bigint,
  'title' : string,
  'period' : string,
  'description' : string,
  'company' : string,
}
export type ExternalBlob = Uint8Array;
export interface Portfolio {
  'about' : About,
  'projects' : Array<Project>,
  'socialLinks' : Array<SocialLink>,
  'contactEmail' : string,
  'experiences' : Array<Experience>,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'screenshots' : [] | [Array<ExternalBlob>],
  'roleDetails' : string,
}
export interface SocialLink { 'url' : string, 'platform' : string }
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProject' : ActorMethod<
    [string, string, string, [] | [Array<ExternalBlob>]],
    Project
  >,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getPortfolioContent' : ActorMethod<[], Portfolio>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'uploadProfileImage' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];